# Generated by Django 5.1.7 on 2025-04-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="user_likes",
            new_name="users_like",
        ),
        migrations.AddField(
            model_name="image",
            name="total_likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
