# Generated by Django 5.1.7 on 2025-04-16 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("courses", "0004_course_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chat_messages",
                to="courses.course",
            ),
        ),
    ]
